### ISSUE TITLE
아이콘 안보임

### ISSUE THREAD

**Issue by JoenSooJoeng** [ClustProject/KWTApptimeseriseVisualization#7]
검색 후에 왼쪽 리스트에는 뜨는데 맵에서는 동그라미에 숫자만 있고 실제 위치가 보이지 않네요.

**Comment by sunkyong** [comment]
동그라미 부분에 뜨는 숫자는 해당 지역의 지점 수이며 동그라미 부분을 클릭하여 맵을 zoom-in하시면 실제 지점의 아이콘이 보입니다.
